### ISSUE TITLE
Default client behaviour

### ISSUE THREAD

**Issue by RayeN** [yola/demands#50]
Our `HTTPServiceClient` derives from `requests.Session` and, as a result, its default behaviour is to share some params, cookies and connection between requests (http://docs.python-requests.org/en/latest/user/advanced/#session-objects).   The default behaviour of requests.get/post/put/delete is to create a new Session for each request.  Taking into account that we usually cache our `demands` based clients on class level and almost never close the session (but `requests` recommend to do that https://github.com/kennethreitz/requests/blob/master/requests/api.py#L49-L51) - I'm concerned that it might be the reason for different bugs/issues etc.

What if we change our base client default behaviour to create a new Session (connection) for each request?  But also leave the possibility to share session between requests (just, for example, when we initialize it in a special way).  So, the same client could work in 2 modes: creating a new session for each request (default) or using shared session (as a context manager).

If my concerns are groundless we can just close this issue and continue to use our demands as we were before.

Thoughts?

ping @blaix, @thomasw, @stefanor, @ekoval

**Comment by alexmojaki** [comment]
1. I don't think that the fact that the top level `requests.get` etc methods create a new `Session` each time should be taken as an indication that this is generally the best way to do things. I see them as simply being convenience methods so that users who want to make a single request to a domain (an extremely common use case) can do so trivially.
2. If you stop persisting parameters between requests you break the API. Demands itself documents:

> Any parameters passed to the constructor will also be used for each and every request

and users have probably noticed that the client subclasses `Session` and used that to persist other things.
3. Not persisting HTTP connections will significantly slow down code which makes many requests.

Are you planning on changing the version to `2.0.0` and breaking compatibility? It seems better to me to have the option to make a new request each time without changing the default.

**Comment by blaix** [comment]
My thoughts mirror Alex's.

What sort of bugs do you think are caused by our current behavior?

**Comment by RayeN** [comment]
1. Right,  and I never said otherwise.  I only mentioned that it's the default behavior of `requests`.

2. Even if we'll follow my suggestion, we won't stop persisting params between requests, thus won't break the documented behavior.  But yes if someone relied on underlying `Session` object - it will break the things.  But I don't think it's something we should be scared of.

3. That's true, but performance it's something vague before it's measured - somehow I think it won't be an issue at all for our case.

I'm not about to break backwards compatibility besides not deriving from `requests.Session`.  
And this ticket was rather about "hey guys, do you think we're doing good?" than "hey, let's change demands default behavior".

> What sort of bugs do you think are caused by our current behavior?

I'm not sure, it's just an assumption (and it can be completely wrong).  But I can think about the following scenario:

 - we open connection (and don't close it)
 - we re-use it
 - connection is closed by server (because of TTL or because of max number connections reached, dunno) just before the next re-usage.

I think urllib connection pool might handle such things.  But anyway, want to hear that I don't need to worry about that :)  So, if everyone is pretty sure that it's not a problem - then we're good and we can close this ticket.

**Comment by ekoval** [comment]
We had few experiments with @RayeN and current behavior seems normal. There is a pool of connections for each session. Once you've created session, it's connections are re-used. So,
```
s = Session('http://www.yola.com')
for i in range(10):
   s.get()
```

Will open two (pool size) connections instead of ten. If connection is not used for some (short) time, it is closed automatically. So it seems like connections pool is quite smart and it is not obligatory a good idea to close session manually each time.

**Comment by thomasw** [comment]
Yeah, I'm pretty sure we're good on the specific scenario @RayeN described. That situation should be handled.

Request's Session implementation also does things like persisting cookies and using them for subsequent requests. For example, if `my_service_instance.service_call1()`gets a response with set cookie headers, then `my_service_instance.service_call2()` will send the cookies up that were set by the first call. That's always seemed like weird default behavior for a service client to me, but it's not particularly problematic for us and might actually be very useful in certain contexts.

Our service clients were never really intended to be used as a context manager as in https://github.com/yola/asyncserver/pull/117/files#diff-ccf24a5864f38636c11411df7fc471a8R20 and the fact that you can is just a side effect of extending Session. I'm assuming @RayeN that you're bringing this up because you don't want to see that pattern repeated? That'd leave two options: continue not closing sessions, don't use service clients as context managers, and know that a single service client instance will share a connection pool (which seems like it's fine considering @ekoval's test and having never historically had problems with not closing them), or make demands explicitly close the sessions like was suggested in the thread that lead to this ticket (which would mean you can't reuse connections like @alexmojaki wants to).

**Comment by RayeN** [comment]
Cool, I think we're good here then.  No need to change anything, at least for now.  Closing.
